---
# Service
apiVersion: v1
kind: Service
metadata:
    name: asklepios-api-setup-service
    namespace: asklepios-sandbox
spec:
    type: ClusterIP
    selector:
        app: asklepios-api-setup
    ports:
        - protocol: TCP
          port: 8082
          targetPort: 8080
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: asklepios-api-setup
    namespace: asklepios-sandbox
spec:
    selector:
        matchLabels:
            app: asklepios-api-setup
    replicas: 1
    template:
        metadata:
            labels:
                app: asklepios-api-setup
        spec:
            containers:
                - name: asklepios-api-setup
                  image: registry.digitalocean.com/asklepios/asklepios-api-setup:017f49985ccbe00c45c69d5b239a9cdbd022f00e
                  env:
                    - name: spring.profiles.active
                      value: stage,api-docs
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                        name: asklepios-api

            imagePullSecrets:
                - name: asklepios

